# Generated by Django 2.0 on 2023-05-04 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'collect_tb',
            },
        ),
        migrations.CreateModel(
            name='dianzan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dz_time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'dianzan_tb',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_text', models.TextField(verbose_name='帖子内容')),
                ('diary_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'Diary_tb',
            },
        ),
        migrations.CreateModel(
            name='goumai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gm_time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='购买时间')),
            ],
            options={
                'verbose_name': '购买历史',
                'verbose_name_plural': '购买历史',
                'db_table': 'goumai_tb',
            },
        ),
        migrations.CreateModel(
            name='liulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ll_time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'db_table': 'liulan_tb',
            },
        ),
        migrations.CreateModel(
            name='pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_pinglun', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'pinglun_tb',
            },
        ),
        migrations.CreateModel(
            name='smartbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('jianjie', models.TextField(verbose_name='简介内容')),
                ('price', models.CharField(max_length=255, verbose_name='价格')),
                ('bookimg', models.FileField(max_length=255, upload_to='book_img/', verbose_name='封面图片')),
                ('bookdata', models.FileField(max_length=255, upload_to='bookdata/', verbose_name='书实体数据')),
                ('label_1', models.CharField(max_length=20, verbose_name='分类标签1')),
                ('label_2', models.CharField(max_length=20, verbose_name='分类标签2')),
                ('label_3', models.CharField(max_length=20, verbose_name='分类标签3')),
                ('dianzan_null', models.CharField(max_length=255, verbose_name='点赞数')),
                ('collect_null', models.CharField(max_length=255, verbose_name='收藏数')),
                ('liulan_null', models.CharField(max_length=255, verbose_name='浏览数')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'smartbook_tb',
            },
        ),
        migrations.CreateModel(
            name='smartUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('sex', models.CharField(max_length=255, verbose_name='性别')),
                ('age', models.CharField(max_length=255, verbose_name='年龄')),
                ('xianju', models.CharField(max_length=255, verbose_name='现居')),
                ('jianjie', models.TextField(verbose_name='简介内容')),
                ('touxiang', models.FileField(max_length=255, upload_to='touxiang/', verbose_name='头像')),
                ('faceimg', models.FileField(max_length=255, upload_to='renlian/', verbose_name='人脸图')),
                ('money', models.CharField(max_length=255, verbose_name='货币余额')),
                ('year', models.CharField(max_length=255, verbose_name='年')),
                ('month', models.CharField(max_length=255, verbose_name='月')),
                ('data', models.CharField(max_length=255, verbose_name='日')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 30, 32, 326659), verbose_name='账户创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'smartUser_tb',
            },
        ),
        migrations.AddField(
            model_name='smartbook',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartUser', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='pinglun',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookmall.smartUser', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='pinglun',
            name='comment_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookmall.smartbook', verbose_name='评论书籍'),
        ),
        migrations.AddField(
            model_name='pinglun',
            name='pre_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookmall.pinglun', verbose_name='父评论id'),
        ),
        migrations.AddField(
            model_name='liulan',
            name='ll_relation_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartbook', verbose_name='那本书'),
        ),
        migrations.AddField(
            model_name='liulan',
            name='who_ll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartUser', verbose_name='谁的'),
        ),
        migrations.AddField(
            model_name='goumai',
            name='gm_relation_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartbook', verbose_name='那本书'),
        ),
        migrations.AddField(
            model_name='goumai',
            name='who_gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartUser', verbose_name='谁的'),
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookmall.smartUser', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='dz_relation_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartbook', verbose_name='那本书'),
        ),
        migrations.AddField(
            model_name='dianzan',
            name='who_dz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartUser', verbose_name='谁的'),
        ),
        migrations.AddField(
            model_name='collect',
            name='clt_relation_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartbook', verbose_name='那本书'),
        ),
        migrations.AddField(
            model_name='collect',
            name='who_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmall.smartUser', verbose_name='谁的'),
        ),
    ]
