# Generated by Django 2.0 on 2022-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WangBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('authors', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='static')),
                ('data', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='WangUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
