# Generated by Django 2.0 on 2022-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaogu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangbooks',
            name='img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
