# Generated by Django 2.0 on 2022-05-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaogu', '0003_auto_20220511_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangbooks',
            name='data',
            field=models.FileField(upload_to='txt/'),
        ),
        migrations.AlterField(
            model_name='wangbooks',
            name='img',
            field=models.FileField(upload_to='img/'),
        ),
    ]
