# Generated by Django 2.0 on 2022-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaogu', '0004_auto_20220511_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=30)),
                ('authors', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
    ]
