# Generated by Django 2.0 on 2022-05-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaogu', '0005_userbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
